"""agregar_referencia_pasarela_a_pagos

Revision ID: 956d536bc27c
Revises: a75c42e1b543
Create Date: 2026-10-01 17:30:02.748758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956d536bc27c'
down_revision = 'a75c42e1b543'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagos', sa.Column('referencia_pasarela', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagos', 'referencia_pasarela')
    # ### end Alembic commands ###